stages:
  - test
  - secret-detection
  - build

variables:
  SECRET_DETECTION_ENABLED: 'true'

include:
  - template: Security/Secret-Detection.gitlab-ci.yml

secret_detection:
  stage: secret-detection
  variables:
    SECRET_DETECTION_HISTORIC_SCAN: 'true'

tests:
  stage: test
  image: rust
  script:
    - cargo test --release

build:amd64:
  stage: build
  image: rust
  script:
    - cargo build --release
  artifacts:
    paths:
      - target/release/outside
